// <auto-generated />
using System;
using DocAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocAPI.Migrations
{
    [DbContext(typeof(PacienteContext))]
    [Migration("20250411194025_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DocAPI.Models.Consulta", b =>
                {
                    b.Property<string>("PacienteID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConsultorioID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Agendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("PacienteID", "ConsultorioID");

                    b.HasIndex("ConsultorioID");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("DocAPI.Models.Consultorio", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("DocAPI.Models.Paciente", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<int?>("Carteira")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RG")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("DocAPI.Models.Consulta", b =>
                {
                    b.HasOne("DocAPI.Models.Consultorio", "Local")
                        .WithMany("Consultas")
                        .HasForeignKey("ConsultorioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocAPI.Models.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("DocAPI.Models.Paciente", b =>
                {
                    b.OwnsOne("DocAPI.Models.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<string>("PacienteID")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("UF")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("PacienteID");

                            b1.ToTable("Pacientes");

                            b1.WithOwner()
                                .HasForeignKey("PacienteID");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("DocAPI.Models.Consultorio", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("DocAPI.Models.Paciente", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
