// <auto-generated />
using System;
using DocAPI.Infrastructure.SqlDb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocAPI.Migrations
{
    [DbContext(typeof(DocDbContext))]
    [Migration("20260416212120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocAPI.Core.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AtestadoStatus")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aviso")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("date");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<string>("InstrucaoStatus")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("InternacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("PacienteID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("ID");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("InternacaoId");

                    b.HasIndex("PacienteID");

                    b.HasIndex("Status");

                    b.HasIndex("Data", "Horario");

                    b.ToTable("Agendamento", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("EtapaAtual")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MensagemParaMedico")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EtapaAtual");

                    b.HasIndex("PacienteId");

                    b.ToTable("Atendimento", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.AtendimentoPendencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.ToTable("AtendimentoPendencias");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.CID", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.HasKey("Codigo");

                    b.ToTable("CID", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ChecklistDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ChecklistDefinition", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ChecklistExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistDefinitionId");

                    b.HasIndex("AtendimentoId", "ChecklistDefinitionId")
                        .IsUnique();

                    b.ToTable("ChecklistExecution", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ChecklistItemDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistDefinitionId");

                    b.HasIndex("ChecklistDefinitionId", "Ordem");

                    b.ToTable("ChecklistItemDefinition", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ChecklistItemExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistItemDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcluidoPor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistExecutionId");

                    b.HasIndex("ChecklistItemDefinitionId");

                    b.HasIndex("ChecklistExecutionId", "ChecklistItemDefinitionId")
                        .IsUnique();

                    b.ToTable("ChecklistItemExecution", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ClinicalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("DataEvento");

                    b.HasIndex("TipoEvento");

                    b.ToTable("ClinicalEvent", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ConciliacaoFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("Periodo");

                    b.ToTable("ConciliacaoFinanceira", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.DemonstrativoFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("DemonstrativoFinanceiro", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Exame", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DataResultado")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataSolicitacao")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(40)");

                    b.HasKey("ID");

                    b.HasIndex("DataSolicitacao");

                    b.HasIndex("ProntuarioId");

                    b.HasIndex("Status");

                    b.ToTable("Exame", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.GuiaFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DemonstrativoFinanceiroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoGuia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoGuiaDescricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DemonstrativoFinanceiroId");

                    b.HasIndex("TipoGuia");

                    b.ToTable("GuiaFinanceira", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Internacao", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CIDCodigo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Carater")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<int>("Diarias")
                        .HasColumnType("int");

                    b.Property<string>("Guia")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("IndicacaoClinica")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TempoDoenca")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("UsaOPME")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CIDCodigo");

                    b.HasIndex("Data");

                    b.HasIndex("ProntuarioId")
                        .IsUnique();

                    b.ToTable("Internacao", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ItemConciliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AtendimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ConciliacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Diferenca")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ItemFinanceiroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ProcedimentoInternacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorEsperado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("ConciliacaoId");

                    b.HasIndex("ItemFinanceiroId");

                    b.HasIndex("ProcedimentoInternacaoId");

                    b.HasIndex("Status");

                    b.HasIndex("AtendimentoId", "Status");

                    b.HasIndex("ConciliacaoId", "Status");

                    b.HasIndex("ItemFinanceiroId", "ConciliacaoId")
                        .IsUnique();

                    b.HasIndex("ItemFinanceiroId", "Status");

                    b.HasIndex("ProcedimentoInternacaoId", "Status");

                    b.HasIndex("Status", "Diferenca")
                        .IsDescending();

                    b.ToTable("ItemConciliacao", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ItemFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<string>("GrauParticipacao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Guia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("GuiaFinanceiraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("HonorarioFator")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Info")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Lote")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NomeUsuario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PercentualVia")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("ServicoCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ServicoDescricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TipoUsuario")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ValorTabela")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Guia");

                    b.HasIndex("GuiaFinanceiraId");

                    b.HasIndex("Lote");

                    b.HasIndex("Protocolo");

                    b.HasIndex("ServicoCodigo");

                    b.HasIndex("Guia", "ServicoCodigo");

                    b.HasIndex("ServicoCodigo", "Data");

                    b.ToTable("ItemFinanceiro", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Paciente", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Carteira")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Plano")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RG")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("Paciente", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ProcedimentoInternacao", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoProcedimento")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("InternacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("InternacaoId");

                    b.ToTable("ProcedimentoInternacao", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Prontuario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("date");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("InformacoesExtras")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProntuarioAnteriorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProntuarioAnteriorId");

                    b.HasIndex("PacienteId", "Versao")
                        .IsUnique();

                    b.ToTable("Prontuario", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ProntuarioAcaoCD", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("ProntuarioAcaoCD", (string)null);
                });

            modelBuilder.Entity("DocAPI.Infrastructure.SqlDb.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("RegistroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ValorNovo")
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DataOperacao");

                    b.HasIndex("Tabela", "RegistroId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Agendamento", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.Atendimento", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocAPI.Core.Entities.Internacao", "Internacao")
                        .WithMany()
                        .HasForeignKey("InternacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocAPI.Core.Entities.Paciente", null)
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteID");

                    b.OwnsOne("DocAPI.Core.Entities.SenhaAgendamento", "SenhaAgendamento", b1 =>
                        {
                            b1.Property<Guid>("AgendamentoID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasColumnType("varchar(20)")
                                .HasColumnName("SenhaAgendamento_Codigo");

                            b1.Property<DateTime?>("DataLiberacao")
                                .HasColumnType("date")
                                .HasColumnName("SenhaAgendamento_DataLiberacao");

                            b1.Property<DateTime>("DataPedido")
                                .HasColumnType("date")
                                .HasColumnName("SenhaAgendamento_DataPedido");

                            b1.Property<DateTime?>("Validade")
                                .HasColumnType("date")
                                .HasColumnName("SenhaAgendamento_Validade");

                            b1.HasKey("AgendamentoID");

                            b1.ToTable("Agendamento");

                            b1.WithOwner()
                                .HasForeignKey("AgendamentoID");
                        });

                    b.Navigation("Atendimento");

                    b.Navigation("Internacao");

                    b.Navigation("SenhaAgendamento");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Atendimento", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.Paciente", "Paciente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.AtendimentoPendencia", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.Atendimento", "Atendimento")
                        .WithMany("Pendencias")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ChecklistExecution", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.Atendimento", "Atendimento")
                        .WithMany("Checklists")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocAPI.Core.Entities.ChecklistDefinition", "ChecklistDefinition")
                        .WithMany()
                        .HasForeignKey("ChecklistDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("ChecklistDefinition");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ChecklistItemDefinition", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.ChecklistDefinition", "ChecklistDefinition")
                        .WithMany("Itens")
                        .HasForeignKey("ChecklistDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistDefinition");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ChecklistItemExecution", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.ChecklistExecution", "ChecklistExecution")
                        .WithMany("Itens")
                        .HasForeignKey("ChecklistExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocAPI.Core.Entities.ChecklistItemDefinition", "ChecklistItemDefinition")
                        .WithMany()
                        .HasForeignKey("ChecklistItemDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChecklistExecution");

                    b.Navigation("ChecklistItemDefinition");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ClinicalEvent", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.Atendimento", "Atendimento")
                        .WithMany("Eventos")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Exame", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.Prontuario", "Prontuario")
                        .WithMany("Exames")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.GuiaFinanceira", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.DemonstrativoFinanceiro", "DemonstrativoFinanceiro")
                        .WithMany("Guias")
                        .HasForeignKey("DemonstrativoFinanceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemonstrativoFinanceiro");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Internacao", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.CID", "CID")
                        .WithMany()
                        .HasForeignKey("CIDCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocAPI.Core.Entities.Prontuario", "Prontuario")
                        .WithOne("Internacao")
                        .HasForeignKey("DocAPI.Core.Entities.Internacao", "ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CID");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ItemConciliacao", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.ConciliacaoFinanceira", "Conciliacao")
                        .WithMany("Itens")
                        .HasForeignKey("ConciliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocAPI.Core.Entities.ItemFinanceiro", "ItemFinanceiro")
                        .WithMany()
                        .HasForeignKey("ItemFinanceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conciliacao");

                    b.Navigation("ItemFinanceiro");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ItemFinanceiro", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.GuiaFinanceira", "GuiaFinanceira")
                        .WithMany("Itens")
                        .HasForeignKey("GuiaFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuiaFinanceira");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Paciente", b =>
                {
                    b.OwnsOne("DocAPI.Core.Entities.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("PacienteID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Endereco_Bairro");

                            b1.Property<string>("CEP")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Endereco_CEP");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Endereco_Cidade");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Endereco_Logradouro");

                            b1.Property<string>("Numero")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Endereco_Numero");

                            b1.Property<string>("UF")
                                .HasMaxLength(2)
                                .HasColumnType("nchar(2)")
                                .HasColumnName("Endereco_UF")
                                .IsFixedLength();

                            b1.HasKey("PacienteID");

                            b1.ToTable("Paciente");

                            b1.WithOwner()
                                .HasForeignKey("PacienteID");
                        });

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ProcedimentoInternacao", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.Internacao", "Internacao")
                        .WithMany("Procedimentos")
                        .HasForeignKey("InternacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Internacao");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Prontuario", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.Atendimento", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocAPI.Core.Entities.Paciente", "Paciente")
                        .WithMany("Prontuarios")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocAPI.Core.Entities.Prontuario", "ProntuarioAnterior")
                        .WithMany()
                        .HasForeignKey("ProntuarioAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("DocAPI.Core.Entities.AGO", "AGO", b1 =>
                        {
                            b1.Property<Guid>("ProntuarioID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Amamentacao")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ago_Amamentacao");

                            b1.Property<string>("CCO")
                                .IsRequired()
                                .HasColumnType("varchar(max)")
                                .HasColumnName("Ago_Cco");

                            b1.Property<string>("Coitarca")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ago_Coitarca");

                            b1.Property<string>("DUM")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Ago_DUM");

                            b1.Property<string>("DesejoGestacao")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Ago_DesejoGestacao");

                            b1.Property<string>("IST")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ago_IST");

                            b1.Property<string>("Intercorrencias")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Ago_Intercorrencias");

                            b1.Property<string>("MAC_TRH")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ago_MAC_TRH");

                            b1.Property<string>("Menarca")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Ago_Menarca");

                            b1.Property<string>("Parceiros")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ago_Parceiros");

                            b1.Property<string>("Paridade")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Ago_Paridade");

                            b1.Property<string>("Relacionamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ago_Relacionamento");

                            b1.Property<int>("VacinaHPV")
                                .HasColumnType("int")
                                .HasColumnName("Ago_VacinaHPV");

                            b1.Property<string>("VidaSexual")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ago_VidaSexual");

                            b1.HasKey("ProntuarioID");

                            b1.ToTable("Prontuario");

                            b1.WithOwner()
                                .HasForeignKey("ProntuarioID");
                        });

                    b.OwnsOne("DocAPI.Core.Entities.Antecedentes", "Antecedentes", b1 =>
                        {
                            b1.Property<Guid>("ProntuarioID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Alergias")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Antecedentes_Alergias");

                            b1.Property<string>("Cirurgias")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Antecedentes_Cirurgias");

                            b1.Property<string>("Comorbidades")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Antecedentes_Comorbidades");

                            b1.Property<string>("HabitoIntestinal")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Antecedentes_HabitoIntestinal");

                            b1.Property<string>("Medicacao")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Antecedentes_Medicacao");

                            b1.Property<string>("Neoplasias")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Antecedentes_Neoplasias");

                            b1.Property<string>("Vacinas")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Antecedentes_Vacinas");

                            b1.Property<string>("Vicios")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Antecedentes_Vicios");

                            b1.HasKey("ProntuarioID");

                            b1.ToTable("Prontuario");

                            b1.WithOwner()
                                .HasForeignKey("ProntuarioID");
                        });

                    b.OwnsOne("DocAPI.Core.Entities.AntecedentesFamiliares", "AntecedentesFamiliares", b1 =>
                        {
                            b1.Property<Guid>("ProntuarioID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Comorbidades")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AntecedentesFamiliares_Comorbidades");

                            b1.Property<string>("Neoplasias")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AntecedentesFamiliares_Neoplasias");

                            b1.HasKey("ProntuarioID");

                            b1.ToTable("Prontuario");

                            b1.WithOwner()
                                .HasForeignKey("ProntuarioID");
                        });

                    b.OwnsOne("DocAPI.Core.Entities.DescricaoBasica", "DescricaoBasica", b1 =>
                        {
                            b1.Property<Guid>("ProntuarioID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AtividadeFisica")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("DescricaoBasica_AtividadeFisica");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("DescricaoBasica_Cpf");

                            b1.Property<int>("Idade")
                                .HasColumnType("int")
                                .HasColumnName("DescricaoBasica_Idade");

                            b1.Property<string>("NomePaciente")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("DescricaoBasica_NomePaciente");

                            b1.Property<string>("Profissao")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("DescricaoBasica_Profissao");

                            b1.Property<string>("QD")
                                .IsRequired()
                                .HasColumnType("varchar(max)")
                                .HasColumnName("DescricaoBasica_QD");

                            b1.Property<string>("Religiao")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("DescricaoBasica_Religiao");

                            b1.HasKey("ProntuarioID");

                            b1.ToTable("Prontuario");

                            b1.WithOwner()
                                .HasForeignKey("ProntuarioID");
                        });

                    b.OwnsOne("DocAPI.Core.Entities.PosOp", "PosOperatorio", b1 =>
                        {
                            b1.Property<Guid>("ProntuarioID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Conclusao")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("PosOp_Conclusao");

                            b1.Property<string>("ExameMacro")
                                .HasColumnType("varchar(max)")
                                .HasColumnName("PosOp_ExameMacro");

                            b1.Property<string>("PeriodoSeguimento")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PosOp_PeriodoSeguimento");

                            b1.HasKey("ProntuarioID");

                            b1.ToTable("Prontuario");

                            b1.WithOwner()
                                .HasForeignKey("ProntuarioID");
                        });

                    b.Navigation("AGO")
                        .IsRequired();

                    b.Navigation("Antecedentes")
                        .IsRequired();

                    b.Navigation("AntecedentesFamiliares")
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("DescricaoBasica")
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("PosOperatorio");

                    b.Navigation("ProntuarioAnterior");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ProntuarioAcaoCD", b =>
                {
                    b.HasOne("DocAPI.Core.Entities.Prontuario", "Prontuario")
                        .WithMany("AcoesCD")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Atendimento", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Eventos");

                    b.Navigation("Pendencias");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ChecklistDefinition", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ChecklistExecution", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.ConciliacaoFinanceira", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.DemonstrativoFinanceiro", b =>
                {
                    b.Navigation("Guias");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.GuiaFinanceira", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Internacao", b =>
                {
                    b.Navigation("Procedimentos");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Paciente", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Atendimentos");

                    b.Navigation("Prontuarios");
                });

            modelBuilder.Entity("DocAPI.Core.Entities.Prontuario", b =>
                {
                    b.Navigation("AcoesCD");

                    b.Navigation("Exames");

                    b.Navigation("Internacao");
                });
#pragma warning restore 612, 618
        }
    }
}
